$ require "common"

@lpp.import "game/shared/Eye.sys.lh"
@lpp.import "game/shared/Transform.comp.lh"
@lpp.import "game/shared/map/Map.sys.lh"

/* ----------------------------------------------------------------------------
 */
b8 EyeSys::update()
{
  if (auto* transform = tryComp<Transform>(attached))
  {
    view.pos = computeWorldPos(*transform);
    view.rotation = transform->rotation;
  }

  return true;
}

/* ----------------------------------------------------------------------------
 */
void EyeSys::getViewMat(mat3x2* view) const
{
  *view = this->view.getViewMat();
}

/* ----------------------------------------------------------------------------
 */
vec2f EyeSys::screenToWorld(vec2f sp) const
{
  return view.viewportPointToWorld(sp, vec2f(viewport_size));
}

/* ----------------------------------------------------------------------------
 */
vec2f EyeSys::worldToScreen(vec2f wp) const
{
  return view.worldPointToViewport(wp, vec2f(viewport_size));
}
