--- 
--- File that just defines the structure of test build parameters.
---

---@class ecs.test.Params
---
--- The directory in which build artifacts should go.
---@field build_dir string
---
--- Parameters for building lpp files.
---@field lpp_params lake.obj.Lpp.PreprocessParams
---
--- Parameters for building cpp files.
---@field cpp_params lake.obj.Cpp.CompileParams
---
--- Parameters for linking the test exe.
---@field link_params lake.obj.Exe.LinkParams
---
--- Task that all lpp files must declare a dependency on.
--- TODO(sushi) this sucks. Really need to set up lake to support 
---             groups of tasks or something. Before then, though, we should
---             just pass in callbacks to compile different types of files
---             rather than passing in the params and having the tests 
---             do that themselves.
---@field lh_task lake.Task

