$ require "common"

@lpp.import "editor/docs/Test.lh"
@lpp.import "editor/Editor.lh"

#include "math/util.h"

namespace editor
{

/* ----------------------------------------------------------------------------
 */
b8 Test::init()
{
  return true;
}

/* ----------------------------------------------------------------------------
 */
void Test::putUI(ui::UI& ui, const EditorSkinDef& skin)
{
  ui::TextSkin text = skin.text;
  text.align = vec2f(0.5, 0.5);

  ui.putText(ui.getBounds(), "your test here!"_str, text);
}

/* ----------------------------------------------------------------------------
 */
void Test::render(gfx::Vulkan& vk)
{

}

}
