$ require "common"

@lpp.import "editor/docs/Test.lh"
@lpp.import "editor/Editor.lh"

namespace editor
{

/* ----------------------------------------------------------------------------
 */
b8 Test::init()
{
  sde.init();
  SourceDataFile::from(&file, "assets/scenes/Test.scene"_str);
  sde.setSourceData(file.returned_data, &file, "SceneDef"_typeid);

  return true;
}

/* ----------------------------------------------------------------------------
 */
void Test::putUI(ui::UI& ui, const EditorSkinDef& skin)
{
  // ui::TextSkin text = skin.text;
  // text.align = vec2f(0.5, 0.5);
  //
  // ui.putText(ui.getBounds(), "your test here!"_str, text);

  sde.put(ui, ui.getBounds(), skin.sdata_edit);
}

/* ----------------------------------------------------------------------------
 */
void Test::render(gfx::Vulkan& vk)
{

}

}
