/*
 *  Testing for the packing pipeline.
 */

$ local cmn = require "common"

@lpp.import "reflect/Packing.lh"
@lpp.import "graphics/Texture.defs.lh"
@lpp.import "sdata/SourceDataFile.lh"
@lpp.import "sdata/SourceDataEditorSkin.defs.lh"

@lpp.import "Test.defs.lh"

#include "math/Rect.h"
#include "iro/fs/File.h"

@log.import

b8 test()
{
  SourceDataFile testfile;
  if (!SourceDataFile::from(&testfile, "tests/packing/test.data"_str))
    return false;
  defer { testfile.deinit(); };

  reflect::PackedData packed;
  if (!packed.init())
    return @log.error(test, "failed to initialize PackedData\n");
  defer { packed.deinit(); };

  reflect::PackParams pack_params = { &packed };

  if (!reflect::packSourceDataFromType(*testfile.returned_data, pack_params))
    return false;

  auto* result = packed.getDataAs<Basket>();

  @log.info(test, result->fruit.getAs<Banana>()->color, '\n');

  return true;
}

int main()
{
  return test()? 0 : 1;
}
