/*
 *  Testing for the packing pipeline.
 */

$ local cmn = require "common"

@@lpp.import "asset/Packing.lh"
@@lpp.import "graphics/Texture.defs.lh"
@@lpp.import "sdata/SourceDataFile.lh"
@@lpp.import "sdata/SourceDataEditorSkin.defs.lh"

#include "math/Rect.h"
#include "iro/fs/File.h"

@log.ger(test-packing, Debug)

b8 test()
{
  SourceDataFile testfile;
  if (!SourceDataFile::from(&testfile, "tests/packing/test.data"_str))
    return false;
  defer { testfile.deinit(); };

  PackedData packed;
  if (!packed.init())
    return ERROR("failed to initialize PackedData\n");
  defer { packed.deinit(); };

  PackParams pack_params = { &packed };

  if (!packSourceDataFromType(*testfile.returned_data, pack_params))
    return false;

  auto* result = packed.getDataAs<SourceDataEditorSkinDef>();

  INFO(result->vec2_data.min_comp_width, '\n');

  return true;
}

int main()
{
  iro::initializeDefaultLogging();

  return test()? 0 : 1;
}
