$ require "common"

@@lpp.import "graphics/ResourceMgr.lh"

#include "iro/Logger.h"

namespace gfx
{

@log.ger(gfx.rsrcmgr, Debug)

/* ----------------------------------------------------------------------------
 */
b8 ResourceMgr::init()
{
  if (!textures.init())
    return false;

  if (!shaders.init())
    return false;

  if (!fonts.init())
    return false;

  return true;
}

/* ----------------------------------------------------------------------------
 */
void ResourceMgr::deinit()
{
  textures.deinit();
  shaders.deinit();
  fonts.deinit();
}

/* ----------------------------------------------------------------------------
 */
b8 ResourceMgr::loadFontLink(FontLink* font, AssetMgr& assetmgr)
{
  
}

}
