$ local cmn = require "common"

@@lpp.import "sdata/SourceDataFileHandle.lh"
@@lpp.import "sdata/SourceDataFileReg.lh"

/* ----------------------------------------------------------------------------
 */
void SourceDataFileHandle::release()
{
  assert(header && "attempt to release a nil SourceDataFileHandle!");
  if (header->rc.remRef())
    header->reg->releaseSourceDataFile(header);
  header = nullptr;
}
