$ local cmn = require "common"
$ local ast = require "reflect.ast"
$ local clog = require "iro.Logger" ("packing", Verbosity.Debug)
$ local List = require "iro.List"
$ local glob = require "iro.fs.glob"

$$$

local AstContext = require "reflect.AstContext"

local imported = lpp.import "src/game/shared/entity/Entity.defs.lh"

local astctx = require "reflect.AstContext".fromString(tostring(imported))

-- io.write(ast.dump(astctx.translation_unit), '\n')

-- Shorthand helper for looking up a declaration by name.
local function lookup(name)
  return astctx:lookupDecl(name)
end

$$$

