$ local cmn = require "common"
$ local ast = require "reflect.ast"
$ local List = require "iro.List"
$ local glob = require "iro.fs.glob"

$$$

local AstContext = require "reflect.AstContext"

local astctx, imported = require "reflect.AstContext".fromGlobs
{
  "src/graphics/Font.resource.lh"
}

local fr = astctx:lookupTypeDecl "gfx::FontResource"

local ct = fr:findField "compiled_texture"
-- ast.dumpout(ct.type:desugar())

$$$

