/*
 *  Definition of category globals.
 */

$ local lpp = require "lpp"
$ local def = require "tools.loggen.gather"
$ local categories = def._get_categories().list

#include "loggen/log_categories.h"

using namespace iro;

namespace logging
{

$ for cat in categories:each() do

Category cat_$(cat.name) = 
{
  .name = "$(cat.name)"_str,
  .verbosity = Verbosity::$(cat.opts.verbosity),
};

$ end

}
